/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWaterPointsRouteImport } from './routes/_authenticated/app.water-points'
import { Route as AuthenticatedAppVillagesRouteImport } from './routes/_authenticated/app.villages'
import { Route as AuthenticatedAppTechniciansRouteImport } from './routes/_authenticated/app.technicians'
import { Route as AuthenticatedAppQualityRouteImport } from './routes/_authenticated/app.quality'
import { Route as AuthenticatedAppMonitoringRouteImport } from './routes/_authenticated/app.monitoring'
import { Route as AuthenticatedAppMaintenanceRouteImport } from './routes/_authenticated/app.maintenance'
import { Route as AuthenticatedAppDevicesRouteImport } from './routes/_authenticated/app.devices'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated/app.alerts'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWaterPointsRoute =
  AuthenticatedAppWaterPointsRouteImport.update({
    id: '/water-points',
    path: '/water-points',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVillagesRoute =
  AuthenticatedAppVillagesRouteImport.update({
    id: '/villages',
    path: '/villages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTechniciansRoute =
  AuthenticatedAppTechniciansRouteImport.update({
    id: '/technicians',
    path: '/technicians',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQualityRoute = AuthenticatedAppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMonitoringRoute =
  AuthenticatedAppMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMaintenanceRoute =
  AuthenticatedAppMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDevicesRoute = AuthenticatedAppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/devices': typeof AuthenticatedAppDevicesRoute
  '/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/app/monitoring': typeof AuthenticatedAppMonitoringRoute
  '/app/quality': typeof AuthenticatedAppQualityRoute
  '/app/technicians': typeof AuthenticatedAppTechniciansRoute
  '/app/villages': typeof AuthenticatedAppVillagesRoute
  '/app/water-points': typeof AuthenticatedAppWaterPointsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/devices': typeof AuthenticatedAppDevicesRoute
  '/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/app/monitoring': typeof AuthenticatedAppMonitoringRoute
  '/app/quality': typeof AuthenticatedAppQualityRoute
  '/app/technicians': typeof AuthenticatedAppTechniciansRoute
  '/app/villages': typeof AuthenticatedAppVillagesRoute
  '/app/water-points': typeof AuthenticatedAppWaterPointsRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/devices': typeof AuthenticatedAppDevicesRoute
  '/_authenticated/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/_authenticated/app/monitoring': typeof AuthenticatedAppMonitoringRoute
  '/_authenticated/app/quality': typeof AuthenticatedAppQualityRoute
  '/_authenticated/app/technicians': typeof AuthenticatedAppTechniciansRoute
  '/_authenticated/app/villages': typeof AuthenticatedAppVillagesRoute
  '/_authenticated/app/water-points': typeof AuthenticatedAppWaterPointsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/devices'
    | '/app/maintenance'
    | '/app/monitoring'
    | '/app/quality'
    | '/app/technicians'
    | '/app/villages'
    | '/app/water-points'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/devices'
    | '/app/maintenance'
    | '/app/monitoring'
    | '/app/quality'
    | '/app/technicians'
    | '/app/villages'
    | '/app/water-points'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/devices'
    | '/_authenticated/app/maintenance'
    | '/_authenticated/app/monitoring'
    | '/_authenticated/app/quality'
    | '/_authenticated/app/technicians'
    | '/_authenticated/app/villages'
    | '/_authenticated/app/water-points'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/water-points': {
      id: '/_authenticated/app/water-points'
      path: '/water-points'
      fullPath: '/app/water-points'
      preLoaderRoute: typeof AuthenticatedAppWaterPointsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/villages': {
      id: '/_authenticated/app/villages'
      path: '/villages'
      fullPath: '/app/villages'
      preLoaderRoute: typeof AuthenticatedAppVillagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/technicians': {
      id: '/_authenticated/app/technicians'
      path: '/technicians'
      fullPath: '/app/technicians'
      preLoaderRoute: typeof AuthenticatedAppTechniciansRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quality': {
      id: '/_authenticated/app/quality'
      path: '/quality'
      fullPath: '/app/quality'
      preLoaderRoute: typeof AuthenticatedAppQualityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/monitoring': {
      id: '/_authenticated/app/monitoring'
      path: '/monitoring'
      fullPath: '/app/monitoring'
      preLoaderRoute: typeof AuthenticatedAppMonitoringRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/maintenance': {
      id: '/_authenticated/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AuthenticatedAppMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/devices': {
      id: '/_authenticated/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AuthenticatedAppDevicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppDevicesRoute: typeof AuthenticatedAppDevicesRoute
  AuthenticatedAppMaintenanceRoute: typeof AuthenticatedAppMaintenanceRoute
  AuthenticatedAppMonitoringRoute: typeof AuthenticatedAppMonitoringRoute
  AuthenticatedAppQualityRoute: typeof AuthenticatedAppQualityRoute
  AuthenticatedAppTechniciansRoute: typeof AuthenticatedAppTechniciansRoute
  AuthenticatedAppVillagesRoute: typeof AuthenticatedAppVillagesRoute
  AuthenticatedAppWaterPointsRoute: typeof AuthenticatedAppWaterPointsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppDevicesRoute: AuthenticatedAppDevicesRoute,
  AuthenticatedAppMaintenanceRoute: AuthenticatedAppMaintenanceRoute,
  AuthenticatedAppMonitoringRoute: AuthenticatedAppMonitoringRoute,
  AuthenticatedAppQualityRoute: AuthenticatedAppQualityRoute,
  AuthenticatedAppTechniciansRoute: AuthenticatedAppTechniciansRoute,
  AuthenticatedAppVillagesRoute: AuthenticatedAppVillagesRoute,
  AuthenticatedAppWaterPointsRoute: AuthenticatedAppWaterPointsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
