/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWaterPointsRouteImport } from './routes/app.water-points'
import { Route as AppVillagesRouteImport } from './routes/app.villages'
import { Route as AppTechniciansRouteImport } from './routes/app.technicians'
import { Route as AppQualityRouteImport } from './routes/app.quality'
import { Route as AppMonitoringRouteImport } from './routes/app.monitoring'
import { Route as AppMaintenanceRouteImport } from './routes/app.maintenance'
import { Route as AppDevicesRouteImport } from './routes/app.devices'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWaterPointsRoute = AppWaterPointsRouteImport.update({
  id: '/water-points',
  path: '/water-points',
  getParentRoute: () => AppRoute,
} as any)
const AppVillagesRoute = AppVillagesRouteImport.update({
  id: '/villages',
  path: '/villages',
  getParentRoute: () => AppRoute,
} as any)
const AppTechniciansRoute = AppTechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/quality': typeof AppQualityRoute
  '/app/technicians': typeof AppTechniciansRoute
  '/app/villages': typeof AppVillagesRoute
  '/app/water-points': typeof AppWaterPointsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/quality': typeof AppQualityRoute
  '/app/technicians': typeof AppTechniciansRoute
  '/app/villages': typeof AppVillagesRoute
  '/app/water-points': typeof AppWaterPointsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/quality': typeof AppQualityRoute
  '/app/technicians': typeof AppTechniciansRoute
  '/app/villages': typeof AppVillagesRoute
  '/app/water-points': typeof AppWaterPointsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/devices'
    | '/app/maintenance'
    | '/app/monitoring'
    | '/app/quality'
    | '/app/technicians'
    | '/app/villages'
    | '/app/water-points'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/devices'
    | '/app/maintenance'
    | '/app/monitoring'
    | '/app/quality'
    | '/app/technicians'
    | '/app/villages'
    | '/app/water-points'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/devices'
    | '/app/maintenance'
    | '/app/monitoring'
    | '/app/quality'
    | '/app/technicians'
    | '/app/villages'
    | '/app/water-points'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/water-points': {
      id: '/app/water-points'
      path: '/water-points'
      fullPath: '/app/water-points'
      preLoaderRoute: typeof AppWaterPointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/villages': {
      id: '/app/villages'
      path: '/villages'
      fullPath: '/app/villages'
      preLoaderRoute: typeof AppVillagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/technicians': {
      id: '/app/technicians'
      path: '/technicians'
      fullPath: '/app/technicians'
      preLoaderRoute: typeof AppTechniciansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quality': {
      id: '/app/quality'
      path: '/quality'
      fullPath: '/app/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring': {
      id: '/app/monitoring'
      path: '/monitoring'
      fullPath: '/app/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintenance': {
      id: '/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppQualityRoute: typeof AppQualityRoute
  AppTechniciansRoute: typeof AppTechniciansRoute
  AppVillagesRoute: typeof AppVillagesRoute
  AppWaterPointsRoute: typeof AppWaterPointsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppQualityRoute: AppQualityRoute,
  AppTechniciansRoute: AppTechniciansRoute,
  AppVillagesRoute: AppVillagesRoute,
  AppWaterPointsRoute: AppWaterPointsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
